- name: Generate Velociraptor server config
  template:
    src: server.config.j2
    dest: /etc/velociraptor/server.config.yaml
  when: install_server

- name: Deploy Velociraptor server
  docker_container:
    name: velociraptor_server
    image: velociraptor
    state: started
    restart_policy: always
    ports:
      - "8000:8000"
    volumes:
      - /etc/velociraptor/server.config.yaml:/etc/velociraptor/server.config.yaml

- name: Generate Velociraptor client config
  template:
    src: client.config.j2
    dest: /etc/velociraptor/client.config.yaml
  when: not install_server

- name: Deploy Velociraptor agent
  docker_container:
    name: velociraptor_agent
    image: velociraptor
    state: started
    restart_policy: always
    volumes:
      - /etc/velociraptor/client.config.yaml:/etc/velociraptor/client.config.yaml
  environment:
    VELOCIRAPTOR_SERVER: "{{ server_url }}"
