- name: Check if GRR repository directory exists
  stat:
    path: /opt/grr-docker
  register: repo_status

- name: Clone the GRR repository
  git:
    repo: https://github.com/google/grr
    dest: /opt/grr-docker
  when: not repo_status.stat.exists

- name: Generate GRR certificates and keys
  command: ./docker_config_files/init_certs.sh
  args:
    chdir: /opt/grr-docker
  when: not repo_status.stat.exists

- name: Start GRR using Docker Compose
  become: true
  command: docker-compose up -d
  args:
    chdir: /opt/grr-docker

- name: Ensure GRR is running
  command: docker ps -f name=grr
  register: result
  until: result.stdout.find('grr') != -1
  retries: 5
  delay: 10
