- name: Install Docker on Debian-based systems
  apt:
    name: docker.io
    state: present
    update_cache: yes
  when: ansible_os_family == 'Debian'

- name: Install Docker on RedHat-based systems
  yum:
    name: docker
    state: present
    update_cache: yes
  when: ansible_os_family == 'RedHat'

- name: Ensure Docker is running
  service:
    name: docker
    state: started
    enabled: yes
