- name: Install Docker on Debian-based systems
  apt:
    name: docker.io
    state: present
    update_cache: yes
  when: ansible_os_family == 'Debian'

- name: Install Docker on RedHat-based systems
  yum:
    name: docker
    state: present
    update_cache: yes
  when: ansible_os_family == 'RedHat'

- name: Install Docker on Windows
  win_feature:
    name: Containers
    state: present
  when: ansible_os_family == "Windows"

- name: Ensure Docker is running on Linux
  service:
    name: docker
    state: started
    enabled: yes
  when: ansible_os_family in ["Debian", "RedHat"]

- name: Ensure Docker is running on Windows
  win_service:
    name: docker
    start_mode: auto
    state: started
  when: ansible_os_family == "Windows"
