- name: Deploy GRR server on localhost
  hosts: localhost
  become: true
  roles:
    - grr_server

- name: Deploy GRR clients to inventory
  hosts: all
  become: true
  roles:
    - role: grr_client

