- name: Deploy Velociraptor server on localhost
  hosts: localhost
  become: true
  roles:
    - velociraptor_server
    - velociraptor_executables

- name: Deploy Velociraptor clients to inventory
  hosts: all
  become: true
  roles:
    - role: velociraptor_client

