- name: Install Docker
  include_role:
    name: docker

- name: Deploy GRR server in Docker
  docker_container:
    name: grr_server
    image: grr
    state: started
    restart_policy: always
    ports:
      - "8000:8000"
