- hosts: localhost
  become: true
  roles:
    - role: grr
      vars:
        install_server: true
        server_url: "http://localhost:8000"
  tasks:
    - name: Ensure Docker is running
      service:
        name: docker
        state: started
        enabled: yes

- hosts: all
  become: true
  roles:
    - role: grr
      vars:
        install_server: false
        server_url: "http://{{ hostvars['localhost']['ansible_facts']['default_ipv4']['address'] }}:8000"
