- name: Check if Velociraptor Docker repository directory exists
  stat:
    path: /opt/velociraptor-docker
  register: repo_status

- name: Clone the Velociraptor Docker repository
  git:
    repo: https://github.com/weslambert/velociraptor-docker
    dest: /opt/velociraptor-docker
  when: not repo_status.stat.exists

- name: Update the .env file with server settings
  lineinfile:
    path: /opt/velociraptor-docker/.env
    regexp: '^VELOX_SERVER_URL=.*$'
    line: 'VELOX_SERVER_URL=https://192.168.0.110:8000/'

- name: Update the .env file with frontend hostname
  lineinfile:
    path: /opt/velociraptor-docker/.env
    regexp: '^VELOX_FRONTEND_HOSTNAME=.*$'
    line: 'VELOX_FRONTEND_HOSTNAME=192.168.0.110'

- name: Start Velociraptor using Docker Compose
  become: true
  command: docker-compose up -d
  args:
    chdir: /opt/velociraptor-docker

- name: Ensure Velociraptor is running
  command: docker ps -f name=velociraptor
  register: result
  until: result.stdout.find('velociraptor') != -1
  retries: 5
  delay: 10